quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
quarkus.datasource.username=system
quarkus.datasource.password=@Misbah123
quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0